server:
  port: 9001

spring:
  application:
    name: aqbp-auth

  redis:
    host: 127.0.0.1
    port: 6379


  cloud:
    loadbalancer:
      ribbon:
        enabled: false

jwt-privacy-secret: '@qIksZMN!snba0cr'