datasource:
  url: jdbc:mysql://127.0.0.1:3306/aqbp-dev?useUnicode=true&useSSL=false&serverTimeZone=GMT%2B8
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: password

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: password